spring.application.name=project2
server.port=1100

#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#eureka.instance.prefer-ip-address=true
#
## Enable Feign Circuit Breaker
#spring.cloud.openfeign.circuitbreaker.enabled=true
#
## Actuator
#management.health.circuitbreakers.enabled=true
#management.endpoints.web.exposure.include=health,info
#
## Resilience4j Circuit Breaker
#resilience4j.circuitbreaker.instances.project1CB.registerHealthIndicator=true
#resilience4j.circuitbreaker.instances.project1CB.slidingWindowType=COUNT_BASED
#resilience4j.circuitbreaker.instances.project1CB.slidingWindowSize=5
#resilience4j.circuitbreaker.instances.project1CB.failureRateThreshold=50
#resilience4j.circuitbreaker.instances.project1CB.waitDurationInOpenState=10s
#resilience4j.circuitbreaker.instances.project1CB.permittedNumberOfCallsInHalfOpenState=2
#resilience4j.circuitbreaker.instances.project1CB.recordExceptions=java.lang.Exception
